### ISSUE TITLE
Not Native

### ISSUE THREAD

**Issue by ktan17** [malsf21/roebling-mobile#1]
The issue is this is being created in React Native and not native mobile development methods

**Comment by malsf21** [comment]
Ah my apologies. I was trying to apply the React skills I learned in CS 97! The head LA really emphasized how React was used in production apps!

**Comment by ktan17** [comment]
whoever said that sounds like a very silly and uneducated individual

**Comment by ktan17** [comment]
whoever said that sounds like a very silly and uneducated individual
